{
 "title": "Mattermost Performance Monitoring v2",
 "description": "A dashboard to monitor complete Mattermost application performance",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": { "query": "label_values(instance)" } },
   {
    "name": "top_db_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_db_store_time_count{instance=~\"$server\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_db_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_db_store_time_sum{instance=~\"$server\"}[${__range_s}s])) by (method) / sum(increase(mattermost_db_store_time_count{instance=~\"$server\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_api_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_api_time_count{instance=~\"$server\"}[${__range_s}s])) by (handler)))"
    }
   },
   {
    "name": "top_api_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_api_time_sum{instance=~\"$server\"}[${__range_s}s])) by (handler) / sum(increase(mattermost_api_time_count{instance=~\"$server\"}[${__range_s}s])) by (handler)))"
    }
   },
   { "name": "eventType", "label": "eventType", "query": { "query": "label_values(eventType)" } }
  ]
 },
 "panels": [
  {
   "title": "mattermost_api_plugin_time_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mattermost_api_plugin_time_bucket{instance=~\"$server\"}[1m])) by (apiName)",
     "legendFormat": "{{apiName}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "mattermost_websocket_broadcasts_total rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(rate(mattermost_websocket_broadcasts_total{instance=~\"$server\", eventType=~\"$eventType\"}[1m])) by (eventType) > 0",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "mattermost_websocket_broadcasts_buffer_total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mattermost_websocket_broadcasts_buffer_total",
     "legendFormat": "hub-{{hub}}"
    }
   ]
  },
  {
   "title": "Websocket Events Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "rate(mattermost_websocket_events_total{instance=~\"$server\", eventType=~\"$eventType\"}[1m])",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Total Logins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mattermost_login_logins_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Calls per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mattermost_db_store_time_count{instance=~\"$server\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(mattermost_db_store_time_count{instance=~\"$server\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache Mem Invalidate Session ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mattermost_cache_mem_invalidation_session_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mattermost_api_time_bucket{instance=~\"$server\"}[1m])) by (instance,le))",
     "legendFormat": "p50-{{instance}}"
    }
   ]
  },
  {
   "title": "Store latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_db_store_time_bucket{instance=~\"$server\"}[1m])) by (instance,le))",
     "legendFormat": "p99-{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mattermost_db_store_time_bucket{instance=~\"$server\"}[1m])) by (instance,le))",
     "legendFormat": "p50-{{instance}}"
    }
   ]
  },
  {
   "title": "Top 10 DB Calls by Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Top 10 API Requests by Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mattermost_api_time_count{instance=~\"$server\",handler=~\"$top_api_count\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Top 10 DB calls by duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mattermost_db_store_time_sum{instance=~\"$server\",method=~\"$top_db_latency\"}[5m])) by (method) / sum(increase(mattermost_db_store_time_count{instance=~\"$server\",method=~\"$top_db_latency\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Channel Load Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.99,\n  sum by (le, instance)(\n    rate(mattermost_api_time_bucket{instance=~\"$server\",handler=\"getPostsForChannelAroundLastUnread\"}[5m])\n  )\n)",
     "legendFormat": "p99-{{instance}}"
    },
    {
     "expr": "histogram_quantile (\n  0.50,\n  sum by (le, instance)(\n    rate(mattermost_api_time_bucket{instance=~\"$server\",handler=\"getPostsForChannelAroundLastUnread\"}[5m])\n  )\n)",
     "legendFormat": "p50-{{instance}}"
    }
   ]
  },
  {
   "title": "Top 10 API requests by duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mattermost_api_time_sum{instance=~\"$server\",handler=~\"$top_api_latency\"}[5m])) by (handler) / sum(increase(mattermost_api_time_count{instance=~\"$server\",handler=~\"$top_api_latency\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Number of connected devices (WebSocket Connections)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mattermost_http_websockets_total{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_http_websockets_total{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CreatePost duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.99,\n  sum by (le, instance)(\n    rate(mattermost_api_time_bucket{instance=~\"$server\",handler=\"createPost\"}[5m])\n  )\n)",
     "legendFormat": "p99-{{instance}}"
    },
    {
     "expr": "histogram_quantile (\n  0.50,\n  sum by (le, instance)(\n    rate(mattermost_api_time_bucket{instance=~\"$server\",handler=\"createPost\"}[5m])\n  )\n)",
     "legendFormat": "p50-{{instance}}"
    }
   ]
  },
  {
   "title": "Replica Lag",
   "type": "graph",
   "description": "This needs to be configured in config.json for it to work",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mattermost_db_replica_lag_time{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mattermost_db_master_connections_total)",
     "legendFormat": "master"
    },
    {
     "expr": "sum(mattermost_db_read_replica_connections_total)",
     "legendFormat": "replica"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Cluster Health",
   "type": "graph",
   "description": "Lower numbers are better, and zero means \"totally healthy\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mattermost_cluster_cluster_health_score{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_cluster_cluster_request_duration_seconds_bucket{instance=~\"$server\"}[5m])) by (le,instance))",
     "legendFormat": "p99-{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mattermost_cluster_cluster_request_duration_seconds_bucket{instance=~\"$server\"}[5m])) by (le,instance))",
     "legendFormat": "p50-{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mattermost_cluster_cluster_request_duration_seconds_count{instance=~\"$server\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(mattermost_cluster_cluster_request_duration_seconds_count{instance=~\"$server\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Job Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Active Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mattermost_jobs_active{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_jobs_active{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "CPU Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_process_cpu_seconds_total{instance=~\"$server\"}[5m])* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}